target = "linux-x86_64"
os = "linux"
architecture = "x86_64"
vendor = "unknown"
abi = "system-v"
object_format = "elf"
endianness = "little"
pointer_bits = "64"
word_bits = "64"
stack_alignment = "16"
