target = "windows-aarch64"
os = "windows"
architecture = "aarch64"
vendor = "pc"
abi = "ms"
object_format = "pe-coff"
endianness = "little"
pointer_bits = 64
word_bits = 64
c_integer_model = "llp64"
float_format = "binary32"
float_size = 4
float_alignment = 4
float_mant_dig = 24
float_min_exp = -125
float_max_exp = 128
double_format = "binary64"
double_size = 8
double_alignment = 8
double_mant_dig = 53
double_min_exp = -1021
double_max_exp = 1024
long_double_format = "binary64"
long_double_size = 8
long_double_alignment = 8
long_double_mant_dig = 53
long_double_min_exp = -1021
long_double_max_exp = 1024
stack_alignment = 16
symbol_prefix = ""
tls_model = "pe-tls"
linker = "link"
startup_entry = "mainCRTStartup"
system_libraries = ["kernel32"]
features = ["threads", "atomics"]
intrinsics = []
supported_abis = ["c", "system", "cplus", "intrinsic", "runtime"]
