import org.gradle.api.file.DuplicatesStrategy
import org.gradle.jvm.tasks.Jar
import java.time.LocalDateTime
import java.time.format.DateTimeFormatter

plugins {
    kotlin("jvm")
    application
}

application {
    applicationName = "cplus"
    mainClass.set("cplus.cli.MainKt")
}

distributions {
    main {
        distributionBaseName = "cplus"
        contents {
            from(rootProject.file("sdk")) {
                into("sdk")
            }
        }
    }
}

tasks.named<JavaExec>("run") {
    workingDir(rootProject.projectDir)
}

val generatedVersionDirectory = layout.buildDirectory.dir("generated/sources/version/main/kotlin")
val generateBuildVersion by tasks.registering {
    val planFile = rootProject.file("IMPL.PLAN.md")
    inputs.file(planFile)
    outputs.dir(generatedVersionDirectory)
    outputs.upToDateWhen { false }

    doLast {
        fun git(vararg arguments: String): String = runCatching {
            ProcessBuilder(listOf("git", "-C", rootProject.projectDir.absolutePath) + arguments)
                .redirectErrorStream(true)
                .start()
                .let { process ->
                    val result = process.inputStream.bufferedReader().readText().trim()
                    if (process.waitFor() == 0) result else "unknown"
                }
        }.getOrDefault("unknown")

        val commit = git("log", "-1", "--format=%H")
        val shortCommit = git("log", "-1", "--format=%h")
        val commitDate = git("log", "-1", "--date=format:%Y-%m-%d %H:%M:%S", "--format=%cd")
        val buildDate = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"))
        val plan = planFile.readText()
        val codename = Regex("(?m)^Current milestone:\\s*(.+)$").find(plan)
            ?.groupValues?.get(1)?.trim()?.ifBlank { "C+ development" } ?: "C+ development"
        fun quote(value: String) = "\"${value.replace("\\", "\\\\").replace("\"", "\\\"").replace("\$", "\\\$").replace("\n", "\\n")}\""

        val packageDirectory = generatedVersionDirectory.get().dir("cplus/cli").asFile
        packageDirectory.mkdirs()
        packageDirectory.resolve("Version.kt").writeText(
            """
            package cplus.cli

            /** Build metadata generated by Gradle for this CLI artifact. */
            data class Version(
                val gitCommit: String,
                val gitShortCommit: String,
                val gitCommitDate: String,
                val buildDate: String,
                val codename: String
            ) {
                companion object {
                    val current = Version(
                        ${quote(commit)},
                        ${quote(shortCommit)},
                        ${quote(commitDate)},
                        ${quote(buildDate)},
                        ${quote(codename)}
                    )
                }
            }
            """.trimIndent() + "\n"
        )
    }
}

kotlin.sourceSets.named("main") {
    kotlin.srcDir(generatedVersionDirectory)
}

tasks.named("compileKotlin") {
    dependsOn(generateBuildVersion)
}

dependencies {
    implementation(project(":compiler"))
    implementation(project(":language-core"))
    implementation(project(":semantic"))
    implementation(project(":c-backend"))
}

val fatJar by tasks.registering(Jar::class) {
    group = "distribution"
    description = "Build a self-contained C+ CLI executable JAR."
    archiveBaseName.set("cplus-cli")
    archiveClassifier.set("all")
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    isPreserveFileTimestamps = false
    isReproducibleFileOrder = true
    manifest {
        attributes["Main-Class"] = application.mainClass.get()
    }
    dependsOn(tasks.named("classes"))
    from(sourceSets.main.get().output)
    from(configurations.runtimeClasspath.get().map { file ->
        if (file.isDirectory) file else zipTree(file)
    })
}

tasks.named("assemble") {
    dependsOn(fatJar)
}
