/// Portable real-valued mathematics with target ABI precision preserved.
pub double std_math_abs(double value);
pub float std_math_acosf(float value);
pub double std_math_acos(double value);
pub long double std_math_acosl(long double value);
pub float std_math_asinf(float value);
pub double std_math_asin(double value);
pub long double std_math_asinl(long double value);
pub float std_math_atanf(float value);
pub double std_math_atan(double value);
pub long double std_math_atanl(long double value);
pub float std_math_acoshf(float value);
pub double std_math_acosh(double value);
pub long double std_math_acoshl(long double value);
pub float std_math_asinhf(float value);
pub double std_math_asinh(double value);
pub long double std_math_asinhl(long double value);
pub float std_math_atanhf(float value);
pub double std_math_atanh(double value);
pub long double std_math_atanhl(long double value);
pub float std_math_cosf(float value);
pub double std_math_cos(double value);
pub long double std_math_cosl(long double value);
pub float std_math_sinf(float value);
pub double std_math_sin(double value);
pub long double std_math_sinl(long double value);
pub float std_math_tanf(float value);
pub double std_math_tan(double value);
pub long double std_math_tanl(long double value);
pub float std_math_coshf(float value);
pub double std_math_cosh(double value);
pub long double std_math_coshl(long double value);
pub float std_math_sinhf(float value);
pub double std_math_sinh(double value);
pub long double std_math_sinhl(long double value);
pub float std_math_tanhf(float value);
pub double std_math_tanh(double value);
pub long double std_math_tanhl(long double value);
pub float std_math_expf(float value);
pub double std_math_exp(double value);
pub long double std_math_expl(long double value);
pub float std_math_exp2f(float value);
pub double std_math_exp2(double value);
pub long double std_math_exp2l(long double value);
pub float std_math_expm1f(float value);
pub double std_math_expm1(double value);
pub long double std_math_expm1l(long double value);
pub float std_math_logf(float value);
pub double std_math_log(double value);
pub long double std_math_logl(long double value);
pub float std_math_log10f(float value);
pub double std_math_log10(double value);
pub long double std_math_log10l(long double value);
pub float std_math_log1pf(float value);
pub double std_math_log1p(double value);
pub long double std_math_log1pl(long double value);
pub float std_math_log2f(float value);
pub double std_math_log2(double value);
pub long double std_math_log2l(long double value);
pub float std_math_logbf(float value);
pub double std_math_logb(double value);
pub long double std_math_logbl(long double value);
pub float std_math_cbrtf(float value);
pub double std_math_cbrt(double value);
pub long double std_math_cbrtl(long double value);
pub float std_math_fabsf(float value);
pub double std_math_fabs(double value);
pub long double std_math_fabsl(long double value);
pub float std_math_sqrtf(float value);
pub long double std_math_sqrtl(long double value);
pub float std_math_erff(float value);
pub double std_math_erf(double value);
pub long double std_math_erfl(long double value);
pub float std_math_erfcf(float value);
pub double std_math_erfc(double value);
pub long double std_math_erfcl(long double value);
pub float std_math_lgammaf(float value);
pub double std_math_lgamma(double value);
pub long double std_math_lgammal(long double value);
pub float std_math_tgammaf(float value);
pub double std_math_tgamma(double value);
pub long double std_math_tgammal(long double value);
pub float std_math_ceilf(float value);
pub double std_math_ceil(double value);
pub long double std_math_ceill(long double value);
pub float std_math_floorf(float value);
pub double std_math_floor(double value);
pub long double std_math_floorl(long double value);
pub float std_math_nearbyintf(float value);
pub double std_math_nearbyint(double value);
pub long double std_math_nearbyintl(long double value);
pub float std_math_rintf(float value);
pub double std_math_rint(double value);
pub long double std_math_rintl(long double value);
pub float std_math_roundf(float value);
pub double std_math_round(double value);
pub long double std_math_roundl(long double value);
pub float std_math_truncf(float value);
pub double std_math_trunc(double value);
pub long double std_math_truncl(long double value);
pub float std_math_atan2f(float left, float right);
pub double std_math_atan2(double left, double right);
pub long double std_math_atan2l(long double left, long double right);
pub float std_math_fmodf(float left, float right);
pub double std_math_fmod(double left, double right);
pub long double std_math_fmodl(long double left, long double right);
pub float std_math_remainderf(float left, float right);
pub double std_math_remainder(double left, double right);
pub long double std_math_remainderl(long double left, long double right);
pub float std_math_hypotf(float left, float right);
pub double std_math_hypot(double left, double right);
pub long double std_math_hypotl(long double left, long double right);
pub float std_math_powf(float left, float right);
pub double std_math_pow(double left, double right);
pub long double std_math_powl(long double left, long double right);
pub float std_math_copysignf(float left, float right);
pub double std_math_copysign(double left, double right);
pub long double std_math_copysignl(long double left, long double right);
pub float std_math_nextafterf(float left, float right);
pub double std_math_nextafter(double left, double right);
pub long double std_math_nextafterl(long double left, long double right);
pub float std_math_fdimf(float left, float right);
pub double std_math_fdim(double left, double right);
pub long double std_math_fdiml(long double left, long double right);
pub float std_math_fmaxf(float left, float right);
pub double std_math_fmax(double left, double right);
pub long double std_math_fmaxl(long double left, long double right);
pub float std_math_fminf(float left, float right);
pub double std_math_fmin(double left, double right);
pub long double std_math_fminl(long double left, long double right);
pub float std_math_frexpf(float value, int* exponent);
pub double std_math_frexp(double value, int* exponent);
pub long double std_math_frexpl(long double value, int* exponent);
pub float std_math_modff(float value, float* integral);
pub double std_math_modf(double value, double* integral);
pub long double std_math_modfl(long double value, long double* integral);
pub int std_math_ilogbf(float value);
pub int std_math_ilogb(double value);
pub int std_math_ilogbl(long double value);
pub float std_math_ldexpf(float value, int exponent);
pub double std_math_ldexp(double value, int exponent);
pub long double std_math_ldexpl(long double value, int exponent);
pub float std_math_scalbnf(float value, int exponent);
pub double std_math_scalbn(double value, int exponent);
pub long double std_math_scalbnl(long double value, int exponent);
pub float std_math_scalblnf(float value, long int exponent);
pub double std_math_scalbln(double value, long int exponent);
pub long double std_math_scalblnl(long double value, long int exponent);
pub long int std_math_lrintf(float value);
pub long int std_math_lrint(double value);
pub long int std_math_lrintl(long double value);
pub long long int std_math_llrintf(float value);
pub long long int std_math_llrint(double value);
pub long long int std_math_llrintl(long double value);
pub long int std_math_lroundf(float value);
pub long int std_math_lround(double value);
pub long int std_math_lroundl(long double value);
pub long long int std_math_llroundf(float value);
pub long long int std_math_llround(double value);
pub long long int std_math_llroundl(long double value);
pub float std_math_nanf(const char* tag);
pub double std_math_nan(const char* tag);
pub long double std_math_nanl(const char* tag);
pub float std_math_nexttowardf(float value, long double direction);
pub double std_math_nexttoward(double value, long double direction);
pub long double std_math_nexttowardl(long double value, long double direction);
pub float std_math_remquof(float left, float right, int* quotient);
pub double std_math_remquo(double left, double right, int* quotient);
pub long double std_math_remquol(long double left, long double right, int* quotient);
pub float std_math_fmaf(float first, float second, float third);
pub double std_math_fma(double first, double second, double third);
pub long double std_math_fmal(long double first, long double second, long double third);
pub double std_math_sqrt(double value);
